Repository NTMC-Community/MatchZoo, pull requests merged in 2018-06, with the labels that each got.

#140 Feature/dynamic pool div 0
  .gitignore
  matchzoo/layers/DynamicMaxPooling.py
Labels: bug

#157 remove .coverage from root
  .coverage
Labels: enhancement

#159 Feature/base model
  Makefile
  matchzoo/__init__.py
  matchzoo/engine/__init__.py
  matchzoo/engine/base_model.py
  matchzoo/engine/base_task.py
  matchzoo/engine/model_params.py
  matchzoo/models/__init__.py
  matchzoo/models/dense_baseline_model.py
  matchzoo/models/naive_model.py
  matchzoo/tasks/__init__.py
  matchzoo/tasks/binary_classification.py
  matchzoo/tasks/classification.py
  matchzoo/tasks/ranking.py
  matchzoo/tasks/utils.py
  requirements.txt
  tests/unit_test/models/test_base_model.py
  tests/unit_test/models/test_dense_baseline_model.py
  tests/unit_test/models/test_naive_model.py
  tests/unit_test/tasks/test_tasks.py
Labels: 2.0, ready to merge

#165 add pre-processors
  .gitignore
  .travis.yml
  Makefile
  matchzoo/preprocessors.py
  requirements.txt
  setup.py
  tests/unit_test/test_preprocessors.py
Labels: 2.0

#145 Add model in config to prevent overwriting of predict.test.wikiqa.txt
  examples/wikiqa/config/anmm_wikiqa.config
  examples/wikiqa/config/arci_wikiqa.config
  examples/wikiqa/config/arcii_wikiqa.config
  examples/wikiqa/config/bimpm_wikiqa.config
  examples/wikiqa/config/cdssm_wikiqa.config
  examples/wikiqa/config/cdssm_word_wikiqa.config
  examples/wikiqa/config/conv_knrm_wikiqa.config
  examples/wikiqa/config/drmm_tks_wikiqa.config
  examples/wikiqa/config/drmm_wikiqa.config
  examples/wikiqa/config/dssm_wikiqa.config
  examples/wikiqa/config/duet_wikiqa.config
  examples/wikiqa/config/knrm_wikiqa.config
  examples/wikiqa/config/matchpyramid_wikiqa.config
  examples/wikiqa/config/mvlstm_wikiqa.config
Labels: enhancement

#169 Update on parameters and hyper parameter tuner.
  matchzoo/engine/__init__.py
  matchzoo/engine/base_model.py
  matchzoo/engine/hyper_spaces.py
  matchzoo/engine/model_params.py
  matchzoo/engine/param.py
  matchzoo/engine/param_table.py
  matchzoo/engine/tune.py
  matchzoo/models/dense_baseline_model.py
  requirements.txt
  tests/unit_test/engine/test_hyper_spaces.py
  tests/unit_test/models/test_naive_model.py
Labels: 2.0, ready to merge

#191 Feature/misc updates
  matchzoo/engine/base_model.py
  matchzoo/engine/base_task.py
  matchzoo/engine/param_table.py
  matchzoo/models/dense_baseline_model.py
  matchzoo/tasks/classification.py
  matchzoo/tasks/ranking.py
  tests/unit_test/models/test_base_model.py
  tests/unit_test/models/test_dense_baseline_model.py
  tests/unit_test/models/test_models.py
  tests/unit_test/models/test_naive_model.py
Labels: 2.0

#179 add unit-processors
  matchzoo/preprocessors.py
  tests/unit_test/test_preprocessors.py
Labels: 2.0

#196 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 2.0

#193 Refactor output layer
  matchzoo/engine/base_model.py
  matchzoo/engine/base_task.py
  matchzoo/models/dense_baseline_model.py
  matchzoo/models/naive_model.py
  matchzoo/tasks/classification.py
  matchzoo/tasks/ranking.py
  tests/unit_test/tasks/test_tasks.py
Labels: 2.0

#186 add dssm model
  matchzoo/models/__init__.py
  matchzoo/models/dssm_model.py
  tests/unit_test/models/test_models.py
Labels: 2.0

#199 refactor stateful unit, update nletterprocessunit, update unittest
  matchzoo/preprocessors.py
  tests/unit_test/test_preprocessors.py
Labels: 2.0

#192 First design of datapack
  matchzoo/datapack.py
  requirements.txt
  setup.py
  tests/unit_test/test_datapack.py
Labels: 2.0

#209 upadte docstring cross reference for documentation
  docs/source/conf.py
  docs/source/index.rst
  matchzoo/engine/base_model.py
  matchzoo/engine/hyper_spaces.py
  matchzoo/preprocessors.py
Labels: 2.0

#211 restructure docs folder
  docs/Makefile
  docs/source/conf.py
  docs/source/index.rst
Labels: 2.0
