Repository NTMC-Community/MatchZoo, pull requests merged in 2018-05, with the labels that each got.

#117 update ci link
  README.md
Labels: enhancement

#121 remove useless folders
  .gitignore
  .pytest_cache/v/cache/lastfailed
  .pytest_cache/v/cache/nodeids
  MatchZoo.egg-info/PKG-INFO
  MatchZoo.egg-info/SOURCES.txt
  MatchZoo.egg-info/dependency_links.txt
  MatchZoo.egg-info/requires.txt
  MatchZoo.egg-info/top_level.txt
  build/lib/matchzoo/__init__.py
  build/lib/matchzoo/inputs/__init__.py
  build/lib/matchzoo/inputs/list_generator.py
  build/lib/matchzoo/inputs/pair_generator.py
  build/lib/matchzoo/inputs/preprocess.py
  build/lib/matchzoo/layers/DynamicMaxPooling.py
  build/lib/matchzoo/layers/Match.py
  build/lib/matchzoo/layers/MatchTensor.py
  build/lib/matchzoo/layers/NonMasking.py
  build/lib/matchzoo/layers/__init__.py
  build/lib/matchzoo/losses/__init__.py
  build/lib/matchzoo/losses/rank_losses.py
  build/lib/matchzoo/main.py
  build/lib/matchzoo/metrics/__init__.py
  build/lib/matchzoo/metrics/rank_evaluations.py
  build/lib/matchzoo/utils/__init__.py
  build/lib/matchzoo/utils/rank_io.py
  build/lib/matchzoo/utils/utility.py
  dist/MatchZoo-1.0-py2.7.egg
Labels: enhancement

#94 Add correct path and link to readme for detailed inputs
  README.md
Labels: enhancement

#58 a bug in a function not been used
  matchzoo/inputs/list_generator.py
Labels: bug, do not merge

#124 add missing dependencies
  .travis.yml
  Makefile
  matchzoo/models/matchsrnn.py
  requirements.txt
  setup.py
Labels: enhancement

#134 setup docs
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
Labels: 2.0

#144 add first version of contribution guide for 2.0 branch
  CONTRIBUTING.md
Labels: 2.0

#153 Update travis CI file to check only python 3.6.3
  .travis.yml
Labels: enhancement

#151 Feature/base task
  matchzoo/__init__.py
  matchzoo/engine/__init__.py
  matchzoo/engine/base_task.py
  matchzoo/tasks/__init__.py
  matchzoo/tasks/binary_classification.py
  matchzoo/tasks/ranking.py
  matchzoo/tasks/utils.py
  tests/unit_test/engine/test_base_task.py
  tests/unit_test/tasks/test_tasks.py
Labels: 2.0
