Repository NTMC-Community/MatchZoo, pull requests merged in 2018-11, with the labels that each got.

#462 add length in the datapack to support masking
  matchzoo/datapack.py
  matchzoo/generators/list_generator.py
  matchzoo/generators/pair_generator.py
  matchzoo/generators/point_generator.py
  matchzoo/preprocessor/arci_preprocessor.py
  matchzoo/preprocessor/cdssm_preprocessor.py
  matchzoo/preprocessor/dssm_preprocessor.py
  matchzoo/preprocessor/segment.py
  tests/unit_test/generators/test_list_generator.py
  tests/unit_test/generators/test_pair_generator.py
  tests/unit_test/generators/test_point_generator.py
Labels: 2.0, feature proposal

#467 Feature/various update
  matchzoo/__init__.py
  matchzoo/engine/base_generator.py
  matchzoo/engine/base_model.py
  matchzoo/engine/base_task.py
  matchzoo/generators/list_generator.py
  matchzoo/metrics.py
  notebooks/tutorial.ipynb
  notebooks/wikiqa/cdssm.ipynb
  notebooks/wikiqa/dssm.ipynb
Labels: 2.0, enhancement

#470 Feature/refactor many things
  .gitignore
  matchzoo/__init__.py
  matchzoo/data_generator/__init__.py
  matchzoo/data_generator/data_generator.py
  matchzoo/data_pack/__init__.py
  matchzoo/data_pack/build_vocab.py
  matchzoo/data_pack/data_pack.py
  matchzoo/data_pack/pack.py
  matchzoo/data_pack/upsample.py
  matchzoo/engine/__init__.py
  matchzoo/engine/base_generator.py
  matchzoo/engine/base_metric.py
  matchzoo/engine/base_model.py
  matchzoo/engine/base_preprocessor.py
  matchzoo/generators/__init__.py
  matchzoo/generators/list_generator.py
  matchzoo/generators/pair_generator.py
  matchzoo/generators/point_generator.py
  matchzoo/losses/__init__.py
  matchzoo/losses/losses.py
  matchzoo/metrics.py
  matchzoo/metrics/__init__.py
  matchzoo/metrics/average_precision.py
  matchzoo/metrics/discounted_cumulative_gain.py
  matchzoo/metrics/mean_average_precision.py
  matchzoo/metrics/mean_reciprocal_rank.py
  matchzoo/metrics/normalized_discounted_cumulative_gain.py
  matchzoo/metrics/precision.py
  matchzoo/preprocessor/__init__.py
  matchzoo/preprocessor/dssm_preprocessor.py
  matchzoo/preprocessor/segment.py
  matchzoo/preprocessors/__init__.py
  matchzoo/preprocessors/arci_preprocessor.py
  matchzoo/preprocessors/cdssm_preprocessor.py
  matchzoo/preprocessors/dssm_preprocessor.py
  matchzoo/processor_units/__init__.py
  matchzoo/processor_units/chain_transform.py
  matchzoo/processor_units/processor_units.py
  matchzoo/tasks/classification.py
  matchzoo/utils/__init__.py
  matchzoo/utils/util.py
  matchzoo/utils/util_preprocessor.py
  notebooks/tutorial.ipynb
  sandbox.ipynb
Labels: 2.0

#477 add new function on datapack
  matchzoo/data_pack/data_pack.py
Labels: 2.0

#483 add pair_data_generator
  matchzoo/__init__.py
  matchzoo/data_generator/__init__.py
  matchzoo/data_generator/data_generator.py
  matchzoo/data_generator/pair_data_generator.py
  matchzoo/data_pack/__init__.py
  matchzoo/data_pack/reorganize_data_pack_pair_wise.py
Labels: 2.0, feature proposal
