Repository NTMC-Community/MatchZoo, pull requests merged in 2018-10, with the labels that each got.

#375 Hotfix/travis
  requirements.txt
  setup.py
Labels: 2.0

#367 add sliding window unit in preprocess units.
  matchzoo/preprocessor/__init__.py
  matchzoo/preprocessor/process_units.py
  tests/unit_test/preprocess/test_process_units.py
Labels: 2.0

#378 resolve docstring error
  matchzoo/engine/base_preprocessor.py
Labels: 2.0

#376 Refactor/loss
  matchzoo/losses.py
  matchzoo/preprocessor/process_units.py
Labels: 2.0

#382 factor out segmentation from base preprocessor into mixin class
  matchzoo/engine/base_preprocessor.py
  matchzoo/preprocessor/__init__.py
  matchzoo/preprocessor/dssm_preprocessor.py
  matchzoo/preprocessor/segment_mixin.py
Labels: 2.0

#388 refactor generator to split `ids` into `id_left` and `id_right`
  matchzoo/generators/list_generator.py
  matchzoo/generators/pair_generator.py
  matchzoo/generators/point_generator.py
  tests/unit_test/generators/test_list_generator.py
  tests/unit_test/generators/test_pair_generator.py
  tests/unit_test/generators/test_point_generator.py
Labels: 2.0

#363 Feature/arc i preprocessor
  matchzoo/preprocessor/__init__.py
  matchzoo/preprocessor/arci_preprocessor.py
  tests/sample/embed_word.txt
  tests/unit_test/preprocess/test_arci_prerpocessor.py
Labels: 2.0

#392 id_left and id_right in pair_generator
  matchzoo/generators/pair_generator.py
Labels: 2.0

#389 Refactor/dssm preprocessor
  matchzoo/preprocessor/dssm_preprocessor.py
Labels: 2.0

#400 unify import, update version
  matchzoo/losses.py
  matchzoo/preprocessor/dssm_preprocessor.py
  matchzoo/preprocessor/process_units.py
  matchzoo/preprocessor/segment_mixin.py
  matchzoo/version.py
Labels: 2.0

#397 small bug fix and refactoring on arc1 preprocessor.
  matchzoo/preprocessor/arci_preprocessor.py
Labels: 2.0

#396 Feature/ cdssm
  matchzoo/preprocessor/__init__.py
  matchzoo/preprocessor/cdssm_preprocessor.py
  matchzoo/preprocessor/process_units.py
  tests/unit_test/preprocess/test_cdssm_prerpocessor.py
  tests/unit_test/preprocess/test_process_units.py
Labels: 2.0

#401 adapt new generator api
  notebooks/wikiqa/dssm.ipynb
Labels: 2.0

#403 Feature/arci inte test
  matchzoo/models/arci_model.py
  matchzoo/preprocessor/arci_preprocessor.py
  tests/inte_test/test_arci.py
  tests/sample/embed_rank.txt
  tests/unit_test/preprocess/test_arci_prerpocessor.py
Labels: 2.0

#410 Hotfix/update badge link
  README.md
Labels: 2.0

#406 Refactor/preprocessor
  matchzoo/preprocessor/arci_preprocessor.py
  matchzoo/preprocessor/cdssm_preprocessor.py
  matchzoo/preprocessor/dssm_preprocessor.py
  matchzoo/utils/__init__.py
  matchzoo/utils/util_preprocessor.py
  tests/unit_test/preprocess/test_arci_prerpocessor.py
  tests/unit_test/preprocess/test_cdssm_prerpocessor.py
Labels: 2.0

#411 rename NTSC as NTMC
  README.md
Labels: 2.0, ANNOUNCEMENT

#413 factor out context in preprocessor
  matchzoo/preprocessor/arci_preprocessor.py
  matchzoo/preprocessor/cdssm_preprocessor.py
  matchzoo/preprocessor/dssm_preprocessor.py
  matchzoo/utils/util_preprocessor.py
  tests/unit_test/preprocess/test_arci_prerpocessor.py
  tests/unit_test/preprocess/test_cdssm_prerpocessor.py
  tests/unit_test/test_datapack.py
Labels: 2.0

#415 Feature/inte test cdssm
  matchzoo/preprocessor/cdssm_preprocessor.py
  tests/inte_test/test_cdssm.py
  tests/unit_test/preprocess/test_cdssm_prerpocessor.py
Labels: 2.0

#430 Hotfix/require
  requirements.txt
Labels: 2.0

#427 add cdssm notebook
  notebooks/wikiqa/cdssm.ipynb
Labels: 2.0, done

#434 Feature/arci notebook
  notebooks/wikiqa/arci.ipynb
Labels: 2.0

#447 Hotfix/add team in readme
  README.md
  Team.md
  matchzoo/datapack.py
  matchzoo/embedding.py
  matchzoo/engine/base_generator.py
  matchzoo/generators/list_generator.py
  matchzoo/generators/pair_generator.py
  matchzoo/generators/point_generator.py
  matchzoo/metrics.py
  matchzoo/preprocessor/arci_preprocessor.py
  matchzoo/preprocessor/cdssm_preprocessor.py
  matchzoo/preprocessor/process_units.py
Labels: 2.0

#446 adapt new stage api for dssm notebook
  notebooks/wikiqa/dssm.ipynb
Labels: 2.0

#456 remove SlidingWindowUnit
  matchzoo/models/cdssm_model.py
  matchzoo/preprocessor/__init__.py
  matchzoo/preprocessor/cdssm_preprocessor.py
  matchzoo/preprocessor/process_units.py
  tests/unit_test/preprocess/test_cdssm_prerpocessor.py
  tests/unit_test/preprocess/test_process_units.py
Labels: 2.0

#459 resolve nan when tokenization
  matchzoo/preprocessor/segment.py
Labels: 2.0

#449 Feature/base metric
  matchzoo/__init__.py
  matchzoo/engine/__init__.py
  matchzoo/engine/base_metric.py
  matchzoo/engine/base_model.py
  matchzoo/engine/base_task.py
  matchzoo/metrics.py
  matchzoo/models/dense_baseline_model.py
  tests/unit_test/generators/test_base_generator.py
  tests/unit_test/test_metrics.py
Labels: 2.0
