Repository NTMC-Community/MatchZoo, pull requests merged in 2019-01, with the labels that each got.

#534 [HotFix] download glove embedding.
  matchzoo/datasets/embeddings/load_glove_embedding.py
Labels: 2.0

#537 numpy doctest space
  matchzoo/processor_units/processor_units.py
  requirements.txt
  setup.py
Labels: 2.0

#532 [Feature] ArcII tutorial.
  tutorials/arcii.ipynb
Labels: 2.0

#535 Feature/match pyramid tutorial
  matchzoo/__init__.py
  matchzoo/data_generator/__init__.py
  matchzoo/data_generator/dpool_data_generator.py
  matchzoo/layers/__init__.py
  matchzoo/layers/dynamic_pooling_layer.py
  matchzoo/models/__init__.py
  matchzoo/models/match_pyramid.py
  matchzoo/preprocessors/basic_preprocessor.py
  tutorials/matchpyramid.ipynb
Labels: 2.0

#533 [Feature] Add MatchPyramid model.
  matchzoo/data_generator/data_generator_wrapper.py
  matchzoo/layers/__init__.py
  matchzoo/layers/dynamic_pooling_layer.py
  matchzoo/models/__init__.py
  matchzoo/models/match_pyramid.py
Labels: 2.0

#538 Duet tutorial
  matchzoo/models/__init__.py
  matchzoo/models/duet.py
  notebooks/wikiqa/duet.ipynb
  tests/inte_test/test_duet.py
Labels: 2.0

#539 refactor mvlstm
  matchzoo/models/mvlstm.py
  notebooks/wikiqa/mvlstm.ipynb
  tests/inte_test/test_mvlstm.py
Labels: 2.0

#540 Feature/coverage
  .coveragerc
  matchzoo/processor_units/processor_units.py
  tests/unit_test/engine/test_base_task.py
  tests/unit_test/models/test_models.py
  tests/unit_test/processor_units/test_processor_units.py
  tests/unit_test/test_embedding.py
Labels: 2.0

#542 add knrm and conv_knrm tutorial
  matchzoo/models/__init__.py
  matchzoo/models/conv_knrm_model.py
  matchzoo/models/knrm_model.py
  notebooks/wikiqa/conv_knrm.ipynb
  notebooks/wikiqa/knrm.ipynb
Labels: 2.0

#544 fix word hashing bug for dssm model
  matchzoo/preprocessors/dssm_preprocessor.py
  matchzoo/processor_units/processor_units.py
  tests/unit_test/processor_units/test_processor_units.py
Labels: bug

#545 [HotFix] reorganize ipynb
  notebooks/wikiqa/arcii.ipynb
  notebooks/wikiqa/matchpyramid.ipynb
Labels: 2.0

#546 [HotFix] ArcII model name.
  matchzoo/models/__init__.py
  matchzoo/models/arcii.py
  notebooks/wikiqa/arcii.ipynb
  notebooks/wikiqa/matchpyramid.ipynb
  tests/unit_test/models/test_models.py
Labels: 2.0

#548 [Feature] fix evaluate
  notebooks/wikiqa/matchpyramid.ipynb
Labels: 2.0

#547 Feature/matchlstm tutorial
  matchzoo/models/match_lstm.py
  notebooks/wikiqa/match_lstm.ipynb
Labels: 2.0

#554 add contrib
  matchzoo/__init__.py
  matchzoo/contrib/__init__.py
  matchzoo/contrib/layers/__init__.py
  matchzoo/contrib/models/__init__.py
  matchzoo/contrib/models/match_lstm.py
  matchzoo/models/__init__.py
  notebooks/wikiqa/match_lstm.ipynb
Labels: 2.0

#556 add description
  matchzoo/auto/prepare.py
  matchzoo/models/__init__.py
  matchzoo/models/anmm.py
  matchzoo/models/arci.py
  matchzoo/models/arcii.py
  matchzoo/models/cdssm.py
  matchzoo/models/conv_knrm.py
  matchzoo/models/drmmtks.py
  matchzoo/models/dssm.py
  matchzoo/models/duet.py
  matchzoo/models/knrm.py
  matchzoo/models/match_pyramid.py
  matchzoo/preprocessors/naive_preprocessor.py
  notebooks/wikiqa/arci.ipynb
  notebooks/wikiqa/arcii.ipynb
  notebooks/wikiqa/conv_knrm.ipynb
  notebooks/wikiqa/drmmtks.ipynb
  notebooks/wikiqa/duet.ipynb
  notebooks/wikiqa/matchpyramid.ipynb
  notebooks/wikiqa/mvlstm.ipynb
  tests/inte_test/test_cdssm.py
  tests/inte_test/test_drmmtks.py
  tests/inte_test/test_dssm.py
  tests/inte_test/test_duet.py
  tests/unit_test/models/test_models.py
  tutorials/models.ipynb
  tutorials/quick_start.ipynb
Labels: 2.0

#560 upgrade requirements in docs
  docs/requirements.txt
Labels: 2.0

#558 add test for snli dataset
  matchzoo/datasets/snli/load_data.py
  tests/unit_test/test_datasets.py
Labels: 2.0

#559 add dssm notebook
  notebooks/wikiqa/dssm.ipynb
Labels: 2.0

#553 add cdssm notebook
  notebooks/wikiqa/cdssm.ipynb
Labels: 2.0

#557 Feature/drmm tutorial
  matchzoo/__init__.py
  matchzoo/data_generator/__init__.py
  matchzoo/data_generator/histogram_data_generator.py
  matchzoo/embedding.py
  matchzoo/models/drmm.py
  matchzoo/models/drmmtks.py
  matchzoo/preprocessors/basic_preprocessor.py
  matchzoo/processor_units/processor_units.py
  notebooks/wikiqa/drmm.ipynb
  notebooks/wikiqa/drmmtks.ipynb
  notebooks/wikiqa/matchpyramid.ipynb
  tests/unit_test/processor_units/test_processor_units.py
Labels: 2.0

#563 add model save for each callback
  matchzoo/engine/base_model.py
  matchzoo/engine/callbacks.py
  notebooks/wikiqa/drmm.ipynb
Labels: 2.0

#578 Hotfix/verbosity leak
  matchzoo/data_pack/data_pack.py
  matchzoo/engine/base_preprocessor.py
  matchzoo/preprocessors/basic_preprocessor.py
Labels: 2.0, enhancement

#577 Add `to_frame` in parameter table.
  matchzoo/engine/param_table.py
  matchzoo/models/parameter_readme_generator.py
Labels: 2.0, enhancement

#572 Add `reset` method to `Param`.
  matchzoo/engine/param.py
Labels: 2.0, enhancement

#588 update contributing.md
  CONTRIBUTING.md
Labels: 2.1

#590 feature/update_load_data
  matchzoo/datasets/snli/load_data.py
  matchzoo/datasets/toy/__init__.py
  matchzoo/datasets/wiki_qa/load_data.py
  tests/unit_test/test_datasets.py
Labels: 2.1, enhancement

#591 feature/update-losses
  matchzoo/losses/rank_cross_entropy_loss.py
  matchzoo/losses/rank_hinge_loss.py
Labels: 2.1, enhancement

#593 Update README.md
  README.md
Labels: 2.0, enhancement
