Repository NTMC-Community/MatchZoo, pull requests merged in 2019-02, with the labels that each got.

#609 [BugFix] fix dynamic pooling for evaluation
  matchzoo/data_generator/dpool_data_generator.py
  matchzoo/layers/dynamic_pooling_layer.py
  matchzoo/models/match_pyramid.py
  tutorials/wikiqa/matchpyramid.ipynb
Labels: 2.0, bug

#610 Hotfix/matchpyramid
  matchzoo/data_generator/callbacks/dynamic_pooling.py
  matchzoo/layers/dynamic_pooling_layer.py
  matchzoo/models/match_pyramid.py
Labels: 2.1

#621 remove logger module
  matchzoo/__init__.py
  matchzoo/logger.py
  matchzoo/models/anmm.py
  matchzoo/models/drmmtks.py
  matchzoo/models/mvlstm.py
  matchzoo/preprocessors/cdssm_preprocessor.py
  matchzoo/preprocessors/dssm_preprocessor.py
  matchzoo/preprocessors/naive_preprocessor.py
Labels: 2.1

#620 complete exceptional messages
  matchzoo/auto/tuner/tuner.py
  matchzoo/data_generator/data_generator.py
  matchzoo/data_pack/data_pack.py
  matchzoo/datasets/snli/load_data.py
  matchzoo/datasets/toy/__init__.py
  matchzoo/datasets/wiki_qa/load_data.py
  matchzoo/embedding/embedding.py
  matchzoo/engine/base_model.py
  matchzoo/engine/base_preprocessor.py
  matchzoo/engine/param_table.py
  matchzoo/layers/matching_layer.py
  matchzoo/metrics/precision.py
  matchzoo/preprocessors/units/frequency_filter.py
Labels: 2.1

#624 replace read table with read csv for pandas
  matchzoo/datasets/snli/load_data.py
  matchzoo/embedding/embedding.py
Labels: 2.1

#627 replace with make
  .travis.yml
Labels: 2.1

#631 #630 add mean func
  matchzoo/engine/base_model.py
Labels: 2.0

#617 Add data generator legacy support in v2.1.
  matchzoo/__init__.py
  matchzoo/contrib/legacy_data_generator.py
Labels: 2.1
