Repository NTMC-Community/MatchZoo, pull requests merged in 2019-04, with the labels that each got.

#682 Update quick start and models tutorials.
  tutorials/models.ipynb
  tutorials/quick_start.ipynb
Labels: 2.1

#680 Update data handling tutorial.
  tutorials/data_handling.ipynb
Labels: 2.2

#679 Update test models.
  tests/unit_test/models/test_models.py
Labels: 2.2

#681 Fix tuner callback save model must specify path bug.
  matchzoo/auto/tuner/callbacks/save_model.py
Labels: 2.2

#688 Propagate keyword arguments to `keras.layers.Embedding`
  matchzoo/engine/base_model.py
Labels: 2.2

#692 update tutorial of arci,duet,mvlstm
  tutorials/wikiqa/arci.ipynb
  tutorials/wikiqa/duet.ipynb
  tutorials/wikiqa/mvlstm.ipynb
Labels: 2.2

#691 update tutorial of arci,duet,mvlstm
  tutorials/wikiqa/arci.ipynb
  tutorials/wikiqa/duet.ipynb
  tutorials/wikiqa/mvlstm.ipynb
Labels: 2.1

#693 seperate OOV with PAD in the vocabulary
  matchzoo/embedding/embedding.py
  matchzoo/models/mvlstm.py
  matchzoo/preprocessors/basic_preprocessor.py
  matchzoo/preprocessors/cdssm_preprocessor.py
  matchzoo/preprocessors/dssm_preprocessor.py
  matchzoo/preprocessors/units/vocabulary.py
  matchzoo/preprocessors/units/word_hashing.py
  tests/unit_test/test_embedding.py
Labels: 2.2, enhancement

#700 Update doc test for better test coverage and documenation.
  matchzoo/auto/tuner/callbacks/lambda_callback.py
  matchzoo/auto/tuner/callbacks/load_embedding_matrix.py
  matchzoo/data_pack/data_pack.py
Labels: 2.2

#696 Feature/esim2
  matchzoo/contrib/models/__init__.py
  matchzoo/contrib/models/esim.py
Labels: 2.2

#663 add HBMP model
  matchzoo/contrib/models/__init__.py
  matchzoo/contrib/models/hbmp.py
Labels: 2.2

#670 [Feature] Add Match-SRNN model
  matchzoo/contrib/layers/__init__.py
  matchzoo/contrib/layers/matching_tensor_layer.py
  matchzoo/contrib/layers/spatial_gru.py
  matchzoo/contrib/models/__init__.py
  matchzoo/contrib/models/match_srnn.py
  tests/unit_test/test_layers.py
Labels: 2.2

#669 Feature/bimpm
  matchzoo/contrib/layers/__init__.py
  matchzoo/contrib/layers/attention_layer.py
  matchzoo/contrib/layers/multi_perspective_layer.py
  matchzoo/contrib/models/__init__.py
  matchzoo/contrib/models/bimpm.py
  requirements.txt
Labels: 2.2
