Repository NTMC-Community/MatchZoo, pull requests merged in 2019-03, with the labels that each got.

#640 Hotfix/travis
  .travis.yml
  Makefile
Labels: 2.0

#646 fixed the snli load_data.py bug
  matchzoo/datasets/snli/load_data.py
Labels: 2.1, bug

#658 [Feature] ArcII and MatchPyramid Notebook Rearrange
  tutorials/wikiqa/README.rst
  tutorials/wikiqa/arcii.ipynb
  tutorials/wikiqa/matchpyramid.ipynb
Labels: 2.1

#665 Fix number of samples for SNLI in tests.
  tests/unit_test/test_datasets.py
Labels: 2.1, bug

#664 add tutorial for drmm knrm conv_knrm
  tutorials/wikiqa/conv_knrm.ipynb
  tutorials/wikiqa/drmm.ipynb
  tutorials/wikiqa/init.ipynb
  tutorials/wikiqa/knrm.ipynb
Labels: 2.1
